TEXTS = {
    "app.refresh_data": "데이터 새로고침",
    "app.refresh_help": "캐시를 비우고 parquet 버퍼를 다시 불러옵니다.",
    "app.published_chart_missing": "발행된 후보는 불러왔지만, 차트 렌더링에 필요한 상세 parquet 데이터가 없습니다.",
    "app.lightweight_info": "경량 모바일 모드에서는 발행된 오늘 후보만 먼저 불러옵니다. 선택 종목의 상세 히스토리가 필요하면 '차트 보기'를 켜세요.",
    "app.selected": "선택 종목",
    "app.no_data": "불러온 데이터가 없습니다. 일별 다운로더 출력과 parquet 캐시를 확인하세요.",
    "app.no_tickers": "선택한 유니버스에서 종목을 찾지 못했습니다.",
    "app.universe_caption": "유니버스: **{market}** | 최신일: **{latest_date}** | 종목 수: **{tickers:,}** | 행 수: **{rows:,}** | TopN: **{top_n}** ({rank_by} 기준)",
    "app.data_tab_deprecated": "Data 탭은 새 파이프라인에서 더 이상 쓰지 않습니다. 일별 다운로더와 parquet 버퍼를 사용하세요.",

    "sidebar.menu": "메뉴",
    "sidebar.select": "화면 선택",
    "sidebar.tab.scanner": "스캐너",
    "sidebar.tab.browse": "탐색",
    "sidebar.view": "보기",
    "sidebar.lightweight_mode": "경량 모바일 모드",
    "sidebar.lightweight_help": "작은 표를 우선 보여주고, 무거운 차트 렌더링은 기본으로 끕니다.",
    "sidebar.show_chart": "차트 보기",
    "sidebar.show_chart_help": "모바일에서 느릴 경우 끄는 것이 좋습니다.",
    "sidebar.scanner": "스캐너",
    "sidebar.scanner_source": "스캐너 소스",
    "sidebar.scanner_source_help": "미리 계산된 오늘 후보를 빠르게 보거나, 전체 스캐너로 전환할 수 있습니다.",
    "sidebar.source.full": "전체 스캐너",
    "sidebar.source.published": "발행된 오늘 후보",
    "sidebar.published_caption": "발행된 오늘 후보 모드에서는 무거운 스캐너 설정을 숨기고 미리 계산된 결과를 먼저 불러옵니다.",
    "sidebar.market": "시장",
    "sidebar.use_all_tickers": "전체 종목 사용 (Top-N 제한 없음)",
    "sidebar.top_n": "Top N (최신일 시가총액 기준)",
    "sidebar.strategy": "전략",
    "sidebar.kospi_filter": "KOSPI 필터",
    "sidebar.ma20_tolerance": "MA20 허용 오차 (%)",
    "sidebar.stop_lookback": "손절 기준 lookback (일)",
    "sidebar.stop_buffer": "손절 버퍼 (%)",
    "sidebar.target_lookback": "목표가 lookback (일)",
    "sidebar.min_rr": "최소 R/R",
    "sidebar.require_ma5_up": "MA5 상승 조건 사용",
    "sidebar.ma5_up_days": "MA5 상승 일수",
    "sidebar.browse": "탐색",

    "today.title": "오늘 후보",
    "today.overview": "시장 요약",
    "today.market_domestic": "국내 시장",
    "today.market_global": "해외 참고",
    "today.result": "오늘 결과",
    "today.kospi_close": "KOSPI 종가",
    "today.kosdaq_close": "KOSDAQ 종가",
    "today.usdkrw": "달러/원",
    "today.sp500": "S&P 500",
    "today.nasdaq": "나스닥",
    "today.picks": "후보 수",
    "today.actionable": "매매 검토",
    "today.watch": "관찰",
    "today.market_tone": "시장 상태",
    "today.market_tone.positive": "긍정적",
    "today.market_tone.neutral": "중립",
    "today.market_tone.defensive": "방어적",
    "today.market_tone.cautious": "주의",
    "today.market_tone_help": "시장 상태 해석: 긍정적 = 신규 진입 우호, 중립 = A/B만 선별 접근, 방어적 = 관망 또는 비중 축소",
    "today.updated_line": "업데이트 {updated_at} | KOSPI {kospi_count} | KOSDAQ {kosdaq_count} | A {a_count} | B {b_count} | 관찰 {watch_count}",
    "today.no_picks": "현재 일별 결과에 발행된 후보가 없습니다.",
    "today.no_market_picks": "{market}에 해당하는 발행 후보가 없습니다.",
    "today.no_actionable": "오늘은 고신뢰 매매 후보가 없습니다. 필요할 때만 관찰 종목을 확인하세요.",
    "today.pick_list": "후보 목록",
    "today.market_radio": "시장",
    "today.pick_select": "오늘 후보에서 선택",
    "today.selected_pick": "선택 종목",
    "today.show_chart": "차트 보기",
    "today.show_chart_help": "선택 종목의 상세 가격 히스토리와 차트를 불러옵니다.",
    "today.why_selected": "선정 이유",
    "today.risk_flags": "주의 요소",
    "today.financial_flags": "재무 체크",
    "today.sector_flags": "섹터 체크",

    "search.title_browse": "종목 탐색 ({market_label})",
    "search.input": "검색 (티커 또는 종목명)",
    "search.no_match": "검색 결과가 없습니다.",
    "search.select_ticker": "종목 선택",
    "search.naver_link": "네이버 증권 열기",
    "search.naver_help": "선택한 종목을 네이버 금융에서 엽니다.",

    "selected.no_ohlcv": "선택한 종목의 OHLCV 데이터가 없습니다. 날짜 정규화 이후 비어 있습니다.",
    "selected.chart_disabled": "경량 모드에서는 차트 렌더링이 꺼져 있습니다. 필요할 때 '차트 보기'를 켜세요.",
    "selected.latest_close": "최신 종가",
    "selected.latest_date": "최신 일자",
    "selected.rows": "행 수",

    "position.title": "포지션 설정",
    "position.caption": "먼저 진입/손절/목표가를 조정하고, 고급 리스크 설정은 아래에서 펼쳐서 확인하세요.",
    "position.entry": "진입가",
    "position.stop": "손절가",
    "position.target": "목표가",
    "position.risk_expander": "리스크 설정 및 포지션 요약",
    "position.risk_setting": "리스크 설정",
    "position.capital": "자본금 (KRW)",
    "position.risk_per_trade": "트레이드당 리스크 (%)",
    "position.max_invest": "트레이드당 최대 투자 비중 (%)",
    "position.summary": "포지션 요약",
    "position.qty": "수량 (주)",
    "position.invest": "투입 금액 (KRW)",
    "position.risk_budget": "리스크 예산 (KRW)",
    "position.loss_at_stop": "손절 시 손실",
    "position.profit_at_target": "목표가 수익",
    "position.rr": "R/R",
}


def t(key: str, **kwargs) -> str:
    value = TEXTS.get(key, key)
    if kwargs:
        return value.format(**kwargs)
    return value
